[package]
name = "fusion_plus"
version = "1.0.0"
authors = []

[addresses]
coin_addrx = "b56bbecb1105320f538c98931eb637eb216e977bc4c6b83504c43663f4e6b923"
token_addr = "b56bbecb1105320f538c98931eb637eb216e977bc4c6b83504c43663f4e6b923"
swap_addr = "b56bbecb1105320f538c98931eb637eb216e977bc4c6b83504c43663f4e6b923"
fusion_swap_v2_addr = "_"

[dev-addresses]
coin_addrx = "0x42"
token_addr = "0x43"
swap_addr = "0x44"
fusion_swap_v2_addr = "0x45"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
